### ISSUE TITLE
Creating new model

### ISSUE THREAD

**Issue by CedricChing** [ChihebTrabelsi/deep_complex_networks#7]
![selection_002](https://user-images.githubusercontent.com/14818430/28918672-db0b6c2e-787c-11e7-9cd1-b05c57c7e856.png)
Command:   python scripts/run.py train
How can I solve the problem?

**Comment by CedricChing** [comment]
I've solved the problem.THANKS ANYWAY.

**Comment by Mi1234** [comment]
Hi CedricChing:

How did you fix the problem of "ValueError: Operands could not be broadcast together with shapes (32, 16, 44) (32, 16, 22)" after running command:  python scripts/run.py train --model complex?
I am using python2.7, Theano (0.10.0b1), and Keras (2.0.6).

Thanks,
Miranda

**Comment by CedricChing** [comment]
Hello, @Mi1234 !
    The data format of Theano is 'channel_first', but the default setting of keras is 'channel_last', which is the data format of Tensorflow. So the data_format in file '~/.keras/keras.json' should be changed to 'channel_first'. You can follow the instructions here [https://keras.io/backend/#switching-from-one-backend-to-another](url)
    Hope this suggestion can help you.
    Have a good day.
    Cedric

**Comment by Mi1234** [comment]
Thank you very much, CedricChing!
The problem has been solved following you instruction.

Best,
Miranda

**Comment by omair-khalid** [comment]
I am still facing the same issue even after trying this fix. Any further help will be highly appreciated. 
![dnn_valueerror](https://user-images.githubusercontent.com/22388788/35812538-2ce59fc6-0a89-11e8-97ca-9d432abad218.png)
